# BaseFWX - Cryptography Engine
# Copyright (C) 2020-2026  FixCraft Inc.
# Licensed under the GNU General Public License v3.0.

"""Public Python API for BaseFWX."""

from .api_files import (
    LiveDecryptor,
    LiveEncryptor,
    an7_file,
    b512decodefile,
    b512encodefile,
    b512file_decode_bytes,
    b512file_encode_bytes,
    b512handlefile,
    dean7_file,
    fwxAES,
    fwxAES_decrypt_raw,
    fwxAES_decrypt_stream,
    fwxAES_encrypt_raw,
    fwxAES_encrypt_stream,
    fwxAES_live_decrypt_chunks,
    fwxAES_live_decrypt_ffmpeg,
    fwxAES_live_decrypt_stream,
    fwxAES_live_encrypt_chunks,
    fwxAES_live_encrypt_ffmpeg,
    fwxAES_live_encrypt_stream,
    normalize_unwrap,
    normalize_wrap,
    pb512file_decode_bytes,
    pb512file_encode_bytes,
)
from .api_media import jMGd, jMGe, kFAd, kFAe, kFMd, kFMe
from .api_strings import (
    a512decode,
    a512encode,
    b256decode,
    b256encode,
    b512decode,
    b512encode,
    b64decode,
    b64encode,
    bi512encode,
    hash512,
    n10decode,
    n10decode_bytes,
    n10encode,
    n10encode_bytes,
    pb512decode,
    pb512encode,
    uhash513,
)
from .main import basefwx, cli, main
from .plugin import (
    API_VERSION as PLUGIN_API_VERSION,
    BasefwxPlugin,
    BasefwxPluginError,
    NativePluginShim,
    PLUGIN_ID_LEN,
    PluginErrorBadInput,
    PluginErrorBadState,
    PluginErrorGeneric,
    PluginErrorNotSupported,
    PluginErrorOutputTooSmall,
    Position as PluginPosition,
    all_plugins,
    discover as discover_plugins,
    factory_for as plugin_factory_for,
    load_native_plugin,
    register as register_plugin,
    register_native as register_native_plugin,
)
from .version import __version__

__all__ = [
    "__version__",
    "a512decode",
    "a512encode",
    "an7_file",
    "b256decode",
    "b256encode",
    "b512decode",
    "b512decodefile",
    "b512encode",
    "b512encodefile",
    "b512file_decode_bytes",
    "b512file_encode_bytes",
    "b512handlefile",
    "b64decode",
    "b64encode",
    "basefwx",
    "bi512encode",
    "cli",
    "dean7_file",
    "fwxAES",
    "fwxAES_decrypt_raw",
    "fwxAES_decrypt_stream",
    "fwxAES_encrypt_raw",
    "fwxAES_encrypt_stream",
    "fwxAES_live_decrypt_chunks",
    "fwxAES_live_decrypt_ffmpeg",
    "fwxAES_live_decrypt_stream",
    "fwxAES_live_encrypt_chunks",
    "fwxAES_live_encrypt_ffmpeg",
    "fwxAES_live_encrypt_stream",
    "hash512",
    "jMGd",
    "jMGe",
    "kFAd",
    "kFAe",
    "kFMd",
    "kFMe",
    "LiveDecryptor",
    "LiveEncryptor",
    "main",
    "n10decode",
    "n10decode_bytes",
    "n10encode",
    "n10encode_bytes",
    "normalize_unwrap",
    "normalize_wrap",
    "pb512decode",
    "pb512encode",
    "pb512file_decode_bytes",
    "pb512file_encode_bytes",
    "uhash513",
    # plugin SPI (3.7.0)
    "BasefwxPlugin",
    "BasefwxPluginError",
    "NativePluginShim",
    "PLUGIN_API_VERSION",
    "PLUGIN_ID_LEN",
    "PluginErrorBadInput",
    "PluginErrorBadState",
    "PluginErrorGeneric",
    "PluginErrorNotSupported",
    "PluginErrorOutputTooSmall",
    "PluginPosition",
    "all_plugins",
    "discover_plugins",
    "load_native_plugin",
    "plugin_factory_for",
    "register_native_plugin",
    "register_plugin",
]
